### ISSUE TITLE
proper definitions checking

### ISSUE THREAD

**Issue by diggit** [SuperV1234/SSVUtils#3]
in file https://github.com/SuperV1234/SSVUtils/blob/master/include/SSVUtils/Core/Detection/Detection.hpp
you are checking various expressions, eg.: `#if (__linux || __unix || __posix || __LINUX__ || __linux__)`
If you want to check existence of these expressions, it sould be `#if defined(__linux) || defined(__unix) || defined(__posix) || defined(__LINUX__) || defined(__linux__)` and so on.
If you want to check for non zero value, then you should ensure, that expressions are defined with some implicit value. In this case current code remains, but code must precede something like this:
```
#ifndef __posix
    #define __posix 0
#endif
```

**Comment by SuperV1234** [comment]
Thanks for the report. This issue is already fixed in the bleeding-egde branch: (https://github.com/SuperV1234/SSVUtils/blob/optionalHeaderOnly/include/SSVUtils/Core/Detection/Detection.hpp)[Detection.hpp]
