### ISSUE TITLE
filesystem

### ISSUE THREAD

**Issue by cucurbita** [SuperV1234/SSVUtils#5]
Hello,

the problem with all these implementations I see around, people don't care about encodings ; all your paths  are handled as 8bit unknown, you might want an agnostic backend which guarantees encodings, the topic is quite complex especially with windows and some other unixes; 

if you wish we may chat, as a longtime/term application cross-platform dev, it's always been a concern ; the threading/locking has been mostly fixed, for common usage.

here some references (and I am not yet there but know the necessary crap that will come in the way)

first: the streams overload handling utf8-utf16 file paths:
https://github.com/cucurbita/coconut/blob/master/coconut/runtime/base/stream.hpp

second: the unicode strings and collators comparison, encodings:
https://github.com/cucurbita/coconut/blob/master/coconut/runtime/detail/discrete/ustring.hpp

third: the paths, mostly a lightweight parsing utility:
https://github.com/cucurbita/coconut/blob/master/coconut/runtime/detail/discrete/upath.hpp

missing part FS syscalls 

Best.

**Comment by SuperV1234** [comment]
Why was the issue closed?
