### ISSUE TITLE
Don't call Base64 encryption

### ISSUE THREAD

**Issue by milleniumbug** [SuperV1234/SSVUtils#7]
There's no key involved there, so it's not encryption. It's Base64 encoding and decoding. Similarly with MD5. Also with obfuscation.

These seem to be trivial issues, but next time you'll see someone using Base64 to encode and then they'll send confidential data over the wire: you'll cringe.

**Comment by SuperV1234** [comment]
Your concerns are valid - I've written this library a long time ago and the name I chose back then was not appropriate. I've changed the `ssvu::Encryption` namespace to `ssvu::Encoding`, and the `encrypt`/`decrypt` functions to `encode`/`decode`. The terminology is not perfect, as MD5 is an hash function, but I wanted to keep the same physical library structure and namespace structure.
